// ════════════════════════════════════════════════════════
//  problems/chunk_001.js
//
//  ・このファイルを複製して chunk_002.js, chunk_003.js … と増やす
//  ・1ファイルあたり 200〜500 問が目安（ファイルサイズ < 500KB 推奨）
//  ・index.html の PROBLEM_CHUNK_FILES にパスを追記すること
//
//  各問題オブジェクトのフィールド:
//    id         : number   必須 / 全問題でユニーク
//    title      : string   必須 / 問題タイトル
//    genre      : string   必須 / ジャンル（例: "微分法"）
//    difficulty : number   必須 / 難易度 1〜10
//    problem    : string   必須 / 問題文（LaTeX: $...$ / $$...$$）
//    solution   : string   任意 / 解説文
//    university : string   任意 / 大学名
//    year       : number   任意 / 年度（例: 2024）
//    type       : string   任意 / "文系" | "理系" | "共通"
//    term       : string   任意 / "前期" | "後期"
// ════════════════════════════════════════════════════════

(window.PROBLEMS_DATA = window.PROBLEMS_DATA || []).push(

  {
    id: 7,
    title: "円周率",
    genre: "三角関数",
    difficulty: 2,
    type: "理系",
    university: "東大",
    year: 2003,
    term: "前期",
    problem: `円周率が$3.05$より大きいことを証明せよ。`,
    solution: `円に内接する正十二角形を考える。この正十二角形の周長が、$3.10$より大きい事は簡単に示せる。`,
  },
  {
    id: 5,
    title: "整数の性質と最大公約数",
    genre: "場合の数と確率",
    difficulty: 10,
    type: "文系",
    university: "東大",
    year: 2024,
    term: "前期",
    problem: `$n$ を $5$ 以上の奇数とする。平面上の点を中心とする円をとり、それに内接する正 $n$ 角形を考える。 $n$ 個の頂点から異なる $4$ 点を同時に選ぶ。ただし、どの $4$ 点も等確率で選ばれるものとする。選んだ $4$ 点を頂点とする四角形が $O$ を内部に含む確率 $p_{n}$ を求めよ。`,
    solution: `(1) $f(n+1) - f(n) = (n+1)^2+(n+1)+1 - (n^2+n+1) = 2n+2$。\n$d = \\gcd(f(n), f(n+1))$ とおくと $d \\mid f(n+1)-f(n) = 2(n+1)$ かつ $d \\mid f(n)$。\n$f(n) = n^2+n+1$ は奇数なので $d$ は奇数。$d \\mid 2(n+1)$ かつ $d$ 奇数 → $d \\mid (n+1)$。\nまた $f(n) = n(n+1)+1$ より $d \\mid 1$、よって $d=1$。\n\n$$\\gcd(f(n),\\, f(n+1)) = 1$$\n\n(2) $f(1)=3,\\ f(2)=7,\\ f(4)=21$（合成数），$f(5)=31,\\ f(6)=43$ など。\n素数になるのは $n=1,2,5,6,\\ldots$ など（$f(n)$ が素数かどうかは $n$ ごとに確認が必要）。`,
  },
  {
    id: 6,
    title: "三角関数の合成と最大値",
    genre: "数と式",
    difficulty: 2,
    type: "共通",
    university: "一橋大",
    year: 2001,
    term: "後期",
    problem: `mを正の整数とする。$m^{3}$ + $3m^{2}$ + $2m$ + $6$ はある正の整数の $3$ 乗である。 $m$を求めよ。`,
    solution: `$m$ が $5$ 以下であることは、 $3$ 乗の展開公式より導ける。あとは、合同式を使うなり、全て代入するなりすればよい。`,
  },
  {
    id: 1,
    title: "数列の漸化式と一般項",
    genre: "ベクトル",
    difficulty: 10,
    type: "共通",
    university: "東大",
    year: 1961,
    term: "共通",
    problem: `点 $O$ で $60$ °の角をなす半直線 $OX$ , $OY$ と∠ $XOY$ の二等分線 $OZ$ があり、 $OX$ , $OY$ 上に $O$ から $1$ cmの距離にそれぞれ点 $A$ 、 $B$ がある、いま動点 $P$ , $Q$ , $R$ がそれぞれ $A$ , $O$ , $B$ から同時に出発して半直線 $OX$ , $OZ$ , $OY$ 上をそれぞれ毎秒 $1$ cm, $\sqrt{3} $ cm, $2$ cmの速さでOから遠ざかる。( $1$ ) $3$ 点 $P$ , $Q$ , $R$ が一直線上にくるまでの時間および( $2$ ) △ $PQR$ の面積が△ $AOB$ の面積に等しくなるまでの時間を求めよ。`,
    solution: `両辺を $3^{n+1}$ で割って $b_n = \\dfrac{a_n}{3^n}$ とおく。\n\n$$b_{n+1} = \\frac{a_{n+1}}{3^{n+1}} = \\frac{3a_n+2^n}{3^{n+1}} = \\frac{a_n}{3^n} + \\frac{1}{3}\\cdot\\left(\\frac{2}{3}\\right)^n = b_n + \\frac{1}{3}\\left(\\frac{2}{3}\\right)^n$$\n\n累和すると\n$$b_n = b_1 + \\sum_{k=1}^{n-1}\\frac{1}{3}\\left(\\frac{2}{3}\\right)^k = \\frac{1}{3} + \\frac{1}{3}\\cdot\\frac{\\frac{2}{3}\\left(1-\\left(\\frac{2}{3}\\right)^{n-1}\\right)}{1-\\frac{2}{3}}$$\n\n整理すると $b_n = 2\\left(\\frac{2}{3}\\right)^n - 1$、よって\n\n$$a_n = 3^n b_n = 2\\cdot 2^n - 3^n = \\boxed{2^{n+1}-3^n}$$`,
  },
  {
    id: 2,
    title: "微分と極値・グラフ",
    genre: "微分法",
    difficulty: 10,
    type: "共通",
    university: "東大",
    year: 1961,
    term: "前期",
    problem: `xの4次式 $f(x)$ において $f(- 0.2) = 2.226$ 、 $f(- 0.1) = 2.460$ 、 $f(0) = 2.718$ 、 $f(0.1) = 3.004$ 、 $f(0.2) = 3.320$ であるとき、$f'(0)$ を求めよ。`,
    solution: ``,
  },
  {
    id: 3,
    title: "場合の数——組み合わせの個数",
    genre: "場合の数と確率",
    difficulty: 10,
    type: "共通",
    university: "東大",
    year: 1961,
    term: "前期",
    problem: `あたえられた半径 $a$ の半球に外接する直円錐をつくり、その全表面積(側面積と底面積の和)をもっとも小さくするには、その高さをなにほどにすればよいか、ただし直円錐の底面は半球の底面とおなじ平面上にあるものとする。`,
    solution: ``,
  },
  {
    id: 4,
    title: "積分と面積",
    genre: "ベクトル",
    difficulty: 10,
    type: "共通",
    university: "東大",
    year: 1961,
    term: "共通",
    problem: `△ $ABC$ の $3$ 辺 $BC$ , $CA$ , $AB$ の上にそれぞれ点 $L$ 、$M$ 、$N$ をとり \n\n$$BL / LC = CM / MA = AN / NB = \frac{1}{2} +\\cdots$$となるようにする。 $AL$ と $CN$ の交点を $P$ 、 $AL$ と $BM$ の交点を $Q$ 、$BM$ と $CN$ の交点を $R$ とするとき、△ $PQR$ の面積と△ $ABC$ の面積との比を求めよ。`,
    solution: `交点：$x^3-3x=kx$ より $x(x^2-(3+k))=0$。\n3 点で交わる条件は $3+k>0$、すなわち $k>-3$。また $k\\ne0$ も必要（$k=0$ は接する）ので $-3<k<0$。\n\n$\\alpha=\\sqrt{3+k}$ とおくと交点は $x=0,\\pm\\alpha$。\n\n$$S(k) = 2\\int_0^{\\alpha}\\bigl|(x^3-3x)-kx\\bigr|\\,dx = 2\\int_0^{\\alpha}(x^3-(3+k)x)\\,dx$$\n\n（$0\\le x\\le\\alpha$ では $C$ が $\\ell$ の下側なので絶対値を外すと符号が逆）\n\n$$= 2\\left[\\frac{x^4}{4}-\\frac{3+k}{2}x^2\\right]_0^{\\alpha} = 2\\left(\\frac{\\alpha^4}{4}-\\frac{\\alpha^2(3+k)}{2}\\right) = \\frac{\\alpha^4}{2}-\\alpha^2(3+k)$$\n\n$\\alpha^2=3+k$ を代入すると\n$$S(k) = \\frac{(3+k)^2}{2}-(3+k)^2 = -\\frac{(3+k)^2}{2}$$\n\n符号を修正して $S(k) = \\dfrac{(3+k)^2}{2}$。`,
  },
  {
    id: 8,
    title: "ベクトルと空間図形",
    genre: "ベクトル",
    difficulty: 7,
    type: "理系",
    university: "東大",
    year: 2023,
    term: "後期",
    problem: `四面体 $OABC$ において $\\overrightarrow{OA}=\\vec{a}$、$\\overrightarrow{OB}=\\vec{b}$、$\\overrightarrow{OC}=\\vec{c}$ とする。\n辺 $OA$、$OB$、$OC$、$AB$、$BC$、$CA$ の長さがすべて等しいとき（正四面体）、\n重心 $G$ から各面への距離が等しいことをベクトルを用いて示せ。`,
    solution: `一辺の長さを 1 とする。重心は $G = \\dfrac{1}{4}(\\vec{a}+\\vec{b}+\\vec{c})$（$O$ を基点）。\n\n面 $OAB$ の法線ベクトルは $\\vec{n}=\\vec{a}\\times\\vec{b}$（外積）。\n\n正四面体の対称性から、$G$ は $O,A,B,C$ から等距離にある。$G$ から各面への距離 $h$ は\n\n$$h = \\frac{3V}{S_{\\text{面}}}$$\n\nここで $V=\\dfrac{\\sqrt{2}}{12}$（正四面体の体積）、$S_{\\text{面}}=\\dfrac{\\sqrt{3}}{4}$（正三角形の面積）。\n\n$$h = \\frac{3\\cdot\\frac{\\sqrt{2}}{12}}{\\frac{\\sqrt{3}}{4}} = \\frac{\\sqrt{2}}{4}\\cdot\\frac{4}{\\sqrt{3}} = \\frac{\\sqrt{6}}{6}$$\n\n対称性より $G$ は 4 面すべてから距離 $\\dfrac{\\sqrt{6}}{6}$ で等しい。$\\blacksquare$`,
  },
  {
    id: 9,
    title: "図形と方程式——円と直線",
    genre: "図形と方程式",
    difficulty: 4,
    type: "文系",
    university: "阪大",
    year: 2024,
    term: "後期",
    problem: `円 $C: x^2+y^2-4x+2y-4=0$ と直線 $\\ell: y=mx+1$ が 2 つの共有点を持つ $m$ の範囲を求めよ。また、2 つの共有点の中点の軌跡を求めよ。`,
    solution: `**円の標準形：** $(x-2)^2+(y+1)^2=9$、中心 $(2,-1)$、半径 $3$。\n\n**2 共有点の条件：** 中心から $\\ell: mx-y+1=0$ への距離 $d < 3$。\n\n$$d = \\frac{|2m+1+1|}{\\sqrt{m^2+1}} = \\frac{|2m+2|}{\\sqrt{m^2+1}} < 3$$\n\n両辺 2 乗：$4(m+1)^2 < 9(m^2+1)$ → $5m^2-8m+5>0$。\n判別式 $= 64-100 < 0$ より常に正。よって**すべての実数 $m$** で 2 共有点を持つ。\n\n**中点の軌跡：** 中点 $(X,Y)$ とおくと、中心と中点を結ぶ線分が弦と直交することから\n$(X-2, Y+1)\\cdot(m,-1)=0$ → $Y+1 = m(X-2)$、かつ $Y=mX+1$。\n連立して $X^2+Y^2-4X+2Y=0$、すなわち $(x-2)^2+(y+1)^2=5$（ただし $m$ が実数全体を動く）。`,
  },
  {
    id: 10,
    title: "確率——反復試行",
    genre: "場合の数と確率",
    difficulty: 5,
    type: "共通",
    university: "東北大",
    year: 2024,
    term: "前期",
    problem: `1 個のサイコロを $n$ 回投げるとき、出た目の最大値がちょうど 5 になる確率 $P_n$ を求めよ。`,
    solution: `「最大値が 5 以下」かつ「最大値が 4 以下」でない確率を取る。\n\n$$P_n = \\left(\\frac{5}{6}\\right)^n - \\left(\\frac{4}{6}\\right)^n = \\left(\\frac{5}{6}\\right)^n - \\left(\\frac{2}{3}\\right)^n$$\n\n**確認：** $n=1$ のとき $P_1 = \\dfrac{5}{6}-\\dfrac{4}{6}=\\dfrac{1}{6}$（5 の目が出る確率）✓`,
  },
  {
    id: 11,
    title: "指数・対数方程式",
    genre: "指数関数・対数関数",
    difficulty: 3,
    type: "文系",
    university: "九大",
    year: 2023,
    term: "前期",
    problem: `次の方程式・不等式を解け。\n(1) $4^x - 3\\cdot 2^{x+1} + 8 = 0$\n(2) $\\log_2(x-1) + \\log_2(x+2) < 3$`,
    solution: `**(1)** $t=2^x$（$t>0$）とおくと $t^2 - 6t + 8 = 0$、$(t-2)(t-4)=0$。\n$t=2$ → $x=1$；$t=4$ → $x=2$。\n\n**解：** $x=1,\\;2$\n\n**(2)** 真数条件：$x>1$。\n$\\log_2(x-1)(x+2) < 3$ より $(x-1)(x+2) < 8$。\n$x^2+x-10 < 0$ → $x = \\dfrac{-1\\pm\\sqrt{41}}{2}$。\n$x>1$ と合わせると\n$$1 < x < \\frac{-1+\\sqrt{41}}{2}$$`,
  },
  {
    id: 12,
    title: "平面ベクトルと内積",
    genre: "ベクトル",
    difficulty: 5,
    type: "共通",
    university: "名大",
    year: 2024,
    term: "後期",
    problem: `$|\\vec{a}|=2$、$|\\vec{b}|=3$、$\\vec{a}\\cdot\\vec{b}=3$ のとき、$\\vec{a}+t\\vec{b}$ の大きさを最小にする実数 $t$ と、そのときの最小値を求めよ。`,
    solution: `$f(t)=|\\vec{a}+t\\vec{b}|^2 = |\\vec{a}|^2 + 2t(\\vec{a}\\cdot\\vec{b}) + t^2|\\vec{b}|^2$\n\n$$= 4 + 6t + 9t^2 = 9\\left(t+\\frac{1}{3}\\right)^2 + 3$$\n\n$t = -\\dfrac{1}{3}$ のとき最小値 $f = 3$。\n\n大きさの最小値は $\\sqrt{3}$。`,
  },
  {
    id: 13,
    title: "複素数平面と回転",
    genre: "平面上の曲線と複素数平面",
    difficulty: 7,
    type: "理系",
    university: "京大",
    year: 2023,
    term: "後期",
    problem: `複素数平面上の点 $z$ が $|z|=1$ を満たすとき、$w=z+\\dfrac{1}{z}$ の描く軌跡を求めよ。`,
    solution: `$z = e^{i\\theta} = \\cos\\theta+i\\sin\\theta$（$\\theta\\in\\mathbb{R}$）とおく。\n\n$$w = z + \\frac{1}{z} = e^{i\\theta}+e^{-i\\theta} = 2\\cos\\theta$$\n\n$w$ は実数であり、$-1\\le\\cos\\theta\\le1$ より $-2\\le w\\le 2$。\n\n**軌跡：** 実軸上の線分 $[-2,\\,2]$。`,
  },
  {
    id: 14,
    title: "データの分析——分散と相関",
    genre: "データの分析",
    difficulty: 2,
    type: "共通",
    university: "東科大",
    year: 2024,
    term: "前期",
    problem: `5 人の生徒のテスト結果（数学、英語）が次のとおりである。\n数学：60, 70, 50, 80, 90\n英語：55, 65, 60, 75, 80\n(1) 数学の平均と分散を求めよ。\n(2) 2 科目の共分散と相関係数を求めよ。`,
    solution: `**(1)** 数学の平均：$\\bar{x}=\\dfrac{60+70+50+80+90}{5}=70$\n\n分散：$s_x^2 = \\dfrac{(-10)^2+0^2+(-20)^2+10^2+20^2}{5}=\\dfrac{900}{5}=180$\n\n**(2)** 英語の平均：$\\bar{y}=\\dfrac{55+65+60+75+80}{5}=67$\n\n共分散：$s_{xy}=\\dfrac{(-10)(-12)+0(-2)+(-20)(-7)+10(8)+20(13)}{5}$\n$=\\dfrac{120+0+140+80+260}{5}=120$\n\n英語の分散：$s_y^2=\\dfrac{144+4+49+64+169}{5}=\\dfrac{430}{5}=86$\n\n相関係数：$r=\\dfrac{120}{\\sqrt{180}\\cdot\\sqrt{86}}=\\dfrac{120}{\\sqrt{15480}}\\approx 0.965$`,
  },
  {
    id: 15,
    title: "極限と無限級数",
    genre: "極限",
    difficulty: 7,
    type: "理系",
    university: "東大",
    year: 2024,
    term: "後期",
    problem: `次の無限級数の和を求めよ。\n$$\\sum_{n=1}^{\\infty} \\frac{n}{2^n}$$`,
    solution: `$S = \\displaystyle\\sum_{n=1}^{\\infty}\\frac{n}{2^n}$ とおく。\n\n$$S = \\frac{1}{2}+\\frac{2}{4}+\\frac{3}{8}+\\cdots$$\n$$\\frac{S}{2} = \\frac{1}{4}+\\frac{2}{8}+\\frac{3}{16}+\\cdots$$\n\n差をとると\n$$\\frac{S}{2} = \\frac{1}{2}+\\frac{1}{4}+\\frac{1}{8}+\\cdots = \\frac{\\frac{1}{2}}{1-\\frac{1}{2}}=1$$\n\nよって $S = \\boxed{2}$。`,
  },
);
